12.0 new invoice theme custom erplibre
ERPLibre/erplibre_theme_addons pull request #3
Opened 2020-09-30 02:56 UTC by Carms-dev

2020-10-31 23:28 UTC, mathben requested changes
I saw that warning when executing
```
2020-10-31 23:00:31,280 38010 INFO BD odoo.modules.loading: loading invoice_template_custom_erplibre/views/report_invoice.xml
2020-10-31 23:00:31,341 38010 WARNING BD odoo.addons.base.models.ir_ui_view: Error-prone use of @class in view Custom template invoice (): use the hasclass(*classes) function to filter elements by their classes 
2020-10-31 23:00:31,387 38010 INFO BD odoo.modules.loading: loading invoice_template_custom_erplibre/views/report_templates.xml 
2020-10-31 23:00:31,697 38010 INFO BD odoo.modules.loading: loading invoice_template_custom_erplibre/data/report_layout.xml 
2020-10-31 23:00:31,705 38010 INFO BD odoo.modules.loading: loading invoice_template_custom_erplibre/report/sale_report_templates.xml 
2020-10-31 23:00:31,725 38010 WARNING BD odoo.addons.base.models.ir_ui_view: Error-prone use of @class in view report_saleorder_document_custom (): use the hasclass(*classes) function to filter elements by their classes 
2020-10-31 23:00:31,725 38010 WARNING BD odoo.addons.base.models.ir_ui_view: Error-prone use of @class in view report_saleorder_document_custom (): use the hasclass(*classes) function to filter elements by their classes 
```

paperformat_id need to be update, where is the documentation to what value to use? Maybe, it's appropriate to set the right value in hook script before installation. Revert it when uninstall.

2020-10-31 23:28 UTC, mathben commented on invoice_template_custom_erplibre/__manifest__.py
> +        'account',
Il semble avoir trop de dépendances?
Puis il manque la dépendance de muk_web_theme

2020-10-31 23:28 UTC, mathben commented on invoice_template_custom_erplibre/views/report_invoice.xml
> +        <xpath expr="//div[@class='page']/h2/span[last()]" position="replace">
if empty, use <xpath [...] /> instead of <xpath [...]></xpath>

2020-10-31 23:28 UTC, mathben commented on invoice_template_custom_erplibre/views/report_invoice.xml
> +<!--        <xpath expr="//t[@t-call='web.external_layout']">-->
To delete before merge. Or do you need it to debug?

2020-10-31 23:28 UTC, mathben commented
SanteLibre is not appropriate in this pull request, I need to merge it before your merge.

2020-11-01 03:23 UTC, mathben commented on invoice_template_custom_erplibre/__manifest__.py
> +        'account',
Mon erreur, il n'y dépend pas.

2020-11-01 03:33 UTC, mathben commented
Need to clean commits and separate 2 modules from pull request

2020-11-01 04:54 UTC, afbenevides commented on invoice_template_custom_erplibre/static/src/scss/layout_custom_erplibre.scss
> +    background-color: darken($o-brand-secondary, 25%);
Should that be primary color?

2020-11-05 01:15 UTC, Carms-dev commented on invoice_template_custom_erplibre/static/src/scss/layout_custom_erplibre.scss
> +    background-color: darken($o-brand-secondary, 25%);
It's a muk variable for the grey

2021-03-07 02:32 UTC, closed without merging